# Data Manipulation with Pandas

In [ ]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abdelrahman\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abdelrahman\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\abdelrahman\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.1-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 1.7 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/11.0 MB 1.5 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/11.0 MB 1.0 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/11.0 MB 1.0 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/11.0 MB 1.0 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/11.0 MB 1.0 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.0 MB 713.8 kB/s eta 0:00:14
   ----- ---------------------------------- 1.6/11.0 MB 776.5 kB/s eta 0:00:13
   ------ --------------------------------- 1.8/11.0 MB 818.3 kB/s eta 0:00:12
   ------- -------------------------------- 2.1/11.0 MB 851.1 kB/s eta 0:00:11
   -------- ------------------------------- 2.4/11.0 MB 883.0 kB/s eta 0:00:10
   -------- ------------------------------- 2.4/11.0 MB 883.0 kB/s eta 0:00:10
   -------- ------------------------------- 2.4/11.0 MB 883.0 kB/s eta 0:00:10
   --------- ------------------------------ 2.6/11.0 MB 798.9 kB/s eta 0:00:11
   --------- ------------------------------ 2.6/11.0 MB 798.9 kB/s eta 0:00:11
   ---------- ----------------------------- 2.9/11.0 MB 795.1 kB/s eta 0:00:11
   ----------- ---------------------------- 3.1/11.0 MB 809.3 kB/s eta 0:00:10
   ------------ --------------------------- 3.4/11.0 MB 825.0 kB/s eta 0:00:10
   ------------- -------------------------- 3.7/11.0 MB 842.1 kB/s eta 0:00:09
   -------------- ------------------------- 3.9/11.0 MB 857.3 kB/s eta 0:00:09
   -------------- ------------------------- 3.9/11.0 MB 857.3 kB/s eta 0:00:09
   --------------- ------------------------ 4.2/11.0 MB 870.7 kB/s eta 0:00:08
   ---------------- ----------------------- 4.5/11.0 MB 888.8 kB/s eta 0:00:08
   ----------------- ---------------------- 4.7/11.0 MB 905.4 kB/s eta 0:00:07
   ------------------ --------------------- 5.0/11.0 MB 909.5 kB/s eta 0:00:07
   ------------------- -------------------- 5.2/11.0 MB 908.2 kB/s eta 0:00:07
   ------------------- -------------------- 5.2/11.0 MB 908.2 kB/s eta 0:00:07
   -------------------- ------------------- 5.8/11.0 MB 929.6 kB/s eta 0:00:06
   --------------------- ------------------ 6.0/11.0 MB 941.6 kB/s eta 0:00:06
   ---------------------- ----------------- 6.3/11.0 MB 952.8 kB/s eta 0:00:05
   ----------------------- ---------------- 6.6/11.0 MB 963.3 kB/s eta 0:00:05
   ------------------------ --------------- 6.8/11.0 MB 966.5 kB/s eta 0:00:05
   ------------------------ --------------- 6.8/11.0 MB 966.5 kB/s eta 0:00:05
   ------------------------- -------------- 7.1/11.0 MB 960.8 kB/s eta 0:00:05
   -------------------------- ------------- 7.3/11.0 MB 967.9 kB/s eta 0:00:04
   --------------------------- ------------ 7.6/11.0 MB 976.6 kB/s eta 0:00:04
   ---------------------------- ----------- 7.9/11.0 MB 986.9 kB/s eta 0:00:04
   ----------------------------- ---------- 8.1/11.0 MB 996.6 kB/s eta 0:00:03
   ------------------------------ --------- 8.4/11.0 MB 1.0 MB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 999.7 kB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 999.7 kB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 986.9 kB/s eta 0:00:03
   --------------------------------- ------ 9.2/11.0 MB 992.1 kB/s eta 0:00:02
   ---------------------------------- ----- 9.4/11.0 MB 997.0 kB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 998.3 kB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 998.3 kB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 998.3 kB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 998.3 kB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 955.0 kB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 955.0 kB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 955.0 kB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 955.0 kB/s eta 0:00:02
   ------------------------------------- -- 10.2/11.0 MB 912.1 kB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 912.6 kB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 912.6 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 902.0 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 902.0 kB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 891.5 kB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.3.1 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\Abdelrahman\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
pd.__version__

'2.3.3'

## **Creating Pandas Data Structures**

### Creating a Pandas Series

A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) of the same type and an associated array of data labels, called its *index*. The simplest Series is formed from only an array of data:

The string representation of a Series displayed interactively shows the index on the left and the values on the right. Since we did not specify an index for the data, a default one consisting of the integers `0` through `N - 1` (where `N` is the length of the data) is created.

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

get the array representation and index object of the Series via its `array` and `index` attributes, respectively:

In [8]:
print(obj.array)
print("=" * 20)
print(obj.values)
print("=" * 20)
print(obj.index)
print("=" * 20)
print(obj.dtype)
print("=" * 20)
print(obj.ndim)
print("=" * 20)
print(obj.shape)
print("=" * 20)
print(obj.size)

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64
====================
[ 4  7 -5  3]
====================
RangeIndex(start=0, stop=4, step=1)
====================
int64
====================
1
====================
(4,)
====================
4

## `pd.Series()`
```python
pd.Series(data=None, index=None, dtype=None, name=None, copy=False)
```

A Series is, in essence, a single column of a DataFrame. So you can assign row labels to the Series the same way as before, using an `index` parameter. However, a Series does not have a column name, it only has one overall `name`:

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
print(obj2)
print(obj2.index)

d    4
b    7
a   -5
c    3
dtype: int64
Index(['d', 'b', 'a', 'c'], dtype='object')

{'d': 4, 'b': 7, 'a': -5, 'c': 3}

In [ ]:
obj2["a"]
obj2["d"] = 6
print(obj2)
obj2[["c", "a", "d"]]
obj2[obj2 > 0]
obj2 * 2

d    6
b    7
a   -5
c    3
dtype: int64

In [52]:
import numpy as np

In [ ]:
np.sqrt(obj2)
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [ ]:
"b" in obj2
"e" in obj2

False

In [3]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [21]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
print(obj3)
obj3.to_dict()
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
print(obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

### The `isna` and `notna` functions in pandas should be used to detect missing data:

In [ ]:
pd.isna(obj4)
pd.notna(obj4)

# or as as instance methods

obj4.isna()
obj4.notna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
obj3
obj4
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

### Both the Series object itself and its index have a `name` attribute, which integrates with other areas of pandas functionality:

In [ ]:
obj4.name = "population"
obj4.index.name = "state"
print(obj4)

In [26]:
obj
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

The Series and the DataFrame are intimately related. It's helpful to think of a DataFrame as actually being just a bunch of Series "glued together".

A DataFrame represents a rectangular table of data and contains an ordered, named collection of columns, each of which can be a different value type (numeric, string, Boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dictionary of Series all sharing the same index.

Creating a DataFrame from a Dictionary

In [27]:
data = {'Name': ['Alice', 'Bob', 'Charlie','sdgagd','dfgadf','sdgv vc','cbzb'],
        'Age': [25, 30, 35,28,72,64,21],
        'City': ['New York', 'Los Angeles', 'Chicago','zxcv','asdf','qwer','bnm,']}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3   sdgagd   28         zxcv
4   dfgadf   72         asdf
5  sdgv vc   64         qwer
6     cbzb   21         bnm,

## **Viewing and Inspecting Data**

#### the **`head`** method selects only the first five rows:

In [ ]:
df.head() # first 5 rows or df.head(n) for first n rows

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3   sdgagd   28         zxcv
4   dfgadf   72         asdf

#### Similarly, **`tail`** returns the last five rows:

In [ ]:
df.tail() # last 5 rows or df.tail(n) for last n rows

#### Getting DataFrame Information

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     7 non-null      int64
 2   City    7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

#### Describing Statistical Information

In [46]:
df.describe()

             Age
count   7.000000
mean   39.285714
std    20.213150
min    21.000000
25%    26.500000
50%    30.000000
75%    49.500000
max    72.000000

#### Unlike Series, DataFrame does not have a `name` attribute. DataFrame's `to_numpy` <U>method</U> returns the data contained in the DataFrame as a two-dimensional ndarray:

In [56]:
df.to_numpy()

array([['Alice', 25],
       ['Bob', 30],
       ['Charlie', 35],
       ['sdgagd', 28],
       ['dfgadf', 72],
       ['sdgv vc', 64],
       ['cbzb', 21]], dtype=object)

In [32]:
pd.DataFrame(df, columns=['Age','Name', 'City'])

   Age     Name         City
0   25    Alice     New York
1   30      Bob  Los Angeles
2   35  Charlie      Chicago
3   28   sdgagd         zxcv
4   72   dfgadf         asdf
5   64  sdgv vc         qwer
6   21     cbzb         bnm,

In [ ]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

In [29]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

If you specify a sequence of columns, the DataFrame’s columns will be arranged in that order:

In [ ]:
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

## **Modifying Data**
Adding a New Column

In [33]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [34]:
frame2["debt"] = ["come", "on", "man", "this", "is", "silly"]
frame2

   year   state  pop   debt
0  2000    Ohio  1.5   come
1  2001    Ohio  1.7     on
2  2002    Ohio  3.6    man
3  2001  Nevada  2.4   this
4  2002  Nevada  2.9     is
5  2003  Nevada  3.2  silly

# **Selecting and Filtering Data**

## Selecting Columns
A column in a DataFrame can be retrieved as a Series either by `dictionary-like` notation or by using the `dot` attribute notation:

In [ ]:
frame2["state"]
frame2.year

## Selectiong Raws
Rows can also be retrieved by position or name with the special `iloc` and `loc` attributes

#### **`loc[]` (Label-based Indexing)**

#### **`iloc[]` (Index-based Indexing)**

In [ ]:
print(frame2)
print(("=" * 20))
print(frame2.loc[0]) # first row  
print(("=" * 20))
print(frame2.loc[1:3]) # rows 1 to 3 inclusive
print(("=" * 20))
print(frame2.loc[[0, 2, 4]]) # rows 0 , 2, and 4
print(("=" * 20))
print(frame2.loc[:,"state"])
print(("=" * 20))
print(frame2.iloc[3]) # fourth row
print(frame2.iloc[:3, :3]) # first 3 rows and first 3 columns
print(("=" * 20))

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: 0, dtype: object
   year state  pop
0  2000  Ohio  1.5
1  2001  Ohio  1.7
2  2002  Ohio  3.6
====================

In [ ]:
frame2["debt"] = np.arange(6.)
frame2
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
frame2["debt"] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

## Filtering Rows Based on Condition

In [47]:
filtered_df = df[df['Age'] > 30]
print(filtered_df)

df.query("Age>25")

      Name  Age     City
2  Charlie   35  Chicago
4   dfgadf   72     asdf
5  sdgv vc   64     qwer

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3   sdgagd   28         zxcv
4   dfgadf   72         asdf
5  sdgv vc   64         qwer

In [ ]:
df[df['Age'] > 30]

      Name  Age     City
2  Charlie   35  Chicago
4   dfgadf   72     asdf
5  sdgv vc   64     qwer

Updating Column Values

In [17]:
df['Age'] = df['Age'] + 1
print(df)

      Name  Age         City  Salary
0    Alice   26     New York   70000
1      Bob   31  Los Angeles   80000
2  Charlie   36      Chicago   90000
3   sdgagd   29         zxcv   20000
4   dfgadf   73         asdf   30000
5  sdgv vc   65         qwer   40000
6     cbzb   22         bnm,   50000

Dropping Columns

In [49]:
#df = df.drop('City',axis=1)
#print(df)

print(df.Age.isnull())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
Name: Age, dtype: bool

In [54]:
del frame2["debt"]
frame2.columns

Index(['year', 'state', 'pop'], dtype='object')

# Comparison: `del` vs. `.drop()` in Pandas

Both `del` and `.drop()` are used to remove data from a DataFrame, but they differ significantly in their functionality, flexibility, and impact on memory.
## 1. `del` (Python Keyword)

**Target**: Specifically designed to delete Columns only.

**Behavior**: It performs an In-place operation, meaning it modifies the original DataFrame immediately.

**Syntax:**
 ```python
 del df['column_name']
 ```

**Limitations**: 
* Cannot delete multiple columns at once.
* Cannot delete rows.
* Does not return any value (returns None).

## 2. `.drop()` (Pandas Method)

**Target**: Highly flexible; can delete both Rows and Columns.

**Behavior**: By default, it returns a new copy of the DataFrame and leaves the original untouched.
    
**Syntax**:
* **For Columns**:
```python
 df.drop(columns=['A', 'B'])
```
*OR*
```python
 df.drop(['A'], axis=1)
 ```

* **For Rows**:
```python
 df.drop(index=[0, 1])
 ```
*OR*
```python
df.drop([0], axis=0)
```
**In-place Modification**: Can modify the original DataFrame if you set the parameter inplace=True.

In [55]:
frame2.T

          0     1     2       3       4       5
year   2000  2001  2002    2001    2002    2003
state  Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
pop     1.5   1.7   3.6     2.4     2.9     3.2

# Some Index methods and properties
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Method/Property</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>append()</code></td>
<td style="text-align: left;">Concatenate with additional Index objects, producing a new Index</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>difference()</code></td>
<td style="text-align: left;">Compute set difference as an Index</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>intersection()</code></td>
<td style="text-align: left;">Compute set intersection</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>union()</code></td>
<td style="text-align: left;">Compute set union</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>isin()</code></td>
<td style="text-align: left;">Compute Boolean array indicating whether each value is contained in the passed collection</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>delete()</code></td>
<td style="text-align: left;">Compute new Index with element at Index <code>i</code> deleted</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>drop()</code></td>
<td style="text-align: left;">Compute new Index by deleting passed values</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>insert()</code></td>
<td style="text-align: left;">Compute new Index by inserting element at Index <code>i</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>is_monotonic</code></td>
<td style="text-align: left;">Returns <code>True</code> if each element is greater than or equal to the previous element</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>is_unique</code></td>
<td style="text-align: left;">Returns <code>True</code> if the Index has no duplicate values</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>unique()</code></td>
<td style="text-align: left;">Compute the array of unique values in the Index</td>
</tr>
</tbody>
</table>

# Possible data inputs to the DataFrame constructor
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2D ndarray</td>
<td style="text-align: left;">A matrix of data, passing optional row and column labels</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dictionary of arrays, lists, or tuples</td>
<td style="text-align: left;">Each sequence becomes a column in the DataFrame; all sequences must be the same length</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NumPy structured/record array</td>
<td style="text-align: left;">Treated as the “dictionary of arrays” case</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dictionary of Series</td>
<td style="text-align: left;">Each value becomes a column; indexes from each Series are unioned together to form the result’s row index if no explicit index is passed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dictionary of dictionaries</td>
<td style="text-align: left;">Each inner dictionary becomes a column; keys are unioned to form the row index as in the “dictionary of Series” case</td>
</tr>
<tr class="even">
<td style="text-align: left;">List of dictionaries or Series</td>
<td style="text-align: left;">Each item becomes a row in the DataFrame; unions of dictionary keys or Series indexes become the DataFrame’s column labels</td>
</tr>
<tr class="odd">
<td style="text-align: left;">List of lists or tuples</td>
<td style="text-align: left;">Treated as the “2D ndarray” case</td>
</tr>
<tr class="even">
<td style="text-align: left;">Another DataFrame</td>
<td style="text-align: left;">The DataFrame’s indexes are used unless different ones are passed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NumPy MaskedArray</td>
<td style="text-align: left;">Like the “2D ndarray” case except masked values are missing in the DataFrame result</td>
</tr>
</tbody>
</table>

# Session 2

#  Reading and Writing Data in Text Format 


<table class="table">
<caption><b>Text and binary data loading functions in pandas</b></caption>
<thead>
<tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>read_csv</code></td>
<td style="text-align: left;">Load delimited data from a file, URL, or file-like object; use comma as default delimiter</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_fwf</code></td>
<td style="text-align: left;">Read data in fixed-width column format (i.e., no delimiters)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>read_clipboard</code></td>
<td style="text-align: left;">Variation of <code>read_csv</code> that reads data from the clipboard; useful for converting tables from web pages</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_excel</code></td>
<td style="text-align: left;">Read tabular data from an Excel XLS or XLSX file</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>read_hdf</code></td>
<td style="text-align: left;">Read HDF5 files written by pandas</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_html</code></td>
<td style="text-align: left;">Read all tables found in the given HTML document</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>read_json</code></td>
<td style="text-align: left;">Read data from a JSON (JavaScript Object Notation) string representation, file, URL, or file-like object</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_feather</code></td>
<td style="text-align: left;">Read the Feather binary file format</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>read_orc</code></td>
<td style="text-align: left;">Read the Apache ORC binary file format</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_parquet</code></td>
<td style="text-align: left;">Read the Apache Parquet binary file format</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>read_pickle</code></td>
<td style="text-align: left;">Read an object stored by pandas using the Python pickle format</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_sas</code></td>
<td style="text-align: left;">Read a SAS dataset stored in one of the SAS system's custom storage formats</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>read_spss</code></td>
<td style="text-align: left;">Read a data file created by SPSS</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_sql</code></td>
<td style="text-align: left;">Read the results of a SQL query (using SQLAlchemy)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>read_sql_table</code></td>
<td style="text-align: left;">Read a whole SQL table (using SQLAlchemy); equivalent to using a query that selects everything in that table using <code>read_sql</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_stata</code></td>
<td style="text-align: left;">Read a dataset from Stata file format</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>read_xml</code></td>
<td style="text-align: left;">Read a table of data from an XML file</td>
</tr>
</tbody>
</table>

In [2]:
pd.read_csv("5_ptyrhon_for_data_analysis/practice_CSVs/employees.csv")

   ID           Name Department  Age  Salary Joining_Date
0   1       John Doe         HR   28   50000   2020-05-21
1   2     Jane Smith         IT   34   75000   2019-06-12
2   3    Bob Johnson    Finance   45   85000   2018-07-15
3   4    Alice White         IT   29   72000   2021-01-04
4   5  Charlie Brown  Marketing   32   68000   2019-11-30
5   6      Eva Green         HR   41   54000   2017-04-22
6   7     Mike Davis    Finance   50   90000   2016-08-19
7   8   Linda Taylor         IT   26   64000   2022-02-10
8   9   James Wilson  Marketing   38   70000   2020-09-08
9  10    Sarah Adams         HR   30   55000   2021-03-18

In [3]:
employees = pd.read_csv("5_ptyrhon_for_data_analysis/practice_CSVs/employees.csv")
print(employees)

   ID           Name Department  Age  Salary Joining_Date
0   1       John Doe         HR   28   50000   2020-05-21
1   2     Jane Smith         IT   34   75000   2019-06-12
2   3    Bob Johnson    Finance   45   85000   2018-07-15
3   4    Alice White         IT   29   72000   2021-01-04
4   5  Charlie Brown  Marketing   32   68000   2019-11-30
5   6      Eva Green         HR   41   54000   2017-04-22
6   7     Mike Davis    Finance   50   90000   2016-08-19
7   8   Linda Taylor         IT   26   64000   2022-02-10
8   9   James Wilson  Marketing   38   70000   2020-09-08
9  10    Sarah Adams         HR   30   55000   2021-03-18

### Displaying Basic Information About the DataFrame

In [8]:
print("DataFrame Information:\n")
employees.info()

DataFrame Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            10 non-null     int64
 1   Name          10 non-null     object
 2   Department    10 non-null     object
 3   Age           10 non-null     int64
 4   Salary        10 non-null     int64
 5   Joining_Date  10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

### viewing DataFrame

In [7]:
employees.head()
employees.tail()

   ID          Name Department  Age  Salary Joining_Date
5   6     Eva Green         HR   41   54000   2017-04-22
6   7    Mike Davis    Finance   50   90000   2016-08-19
7   8  Linda Taylor         IT   26   64000   2022-02-10
8   9  James Wilson  Marketing   38   70000   2020-09-08
9  10   Sarah Adams         HR   30   55000   2021-03-18

### Calculating Basic Statistics for Numerical Columns

In [10]:
print("Statistical Summary:\n")
employees.describe()

Statistical Summary:

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  35.300000  68300.000000
std     3.02765   7.958922  13106.826042
min     1.00000  26.000000  50000.000000
25%     3.25000  29.250000  57250.000000
50%     5.50000  33.000000  69000.000000
75%     7.75000  40.250000  74250.000000
max    10.00000  50.000000  90000.000000

### Filtering Employees by Department

In [ ]:
employees[employees['Department'] == 'IT']
employees[employees['Age'] > 30]
employees

In [35]:
it_employees = employees[employees['Department'] == 'IT']
print("IT Department Employees:\n")
it_employees

IT Department Employees:

   ID          Name Department  Age  Salary Joining_Date
1   2    Jane Smith         IT   34   75000   2019-06-12
3   4   Alice White         IT   29   72000   2021-01-04
7   8  Linda Taylor         IT   26   64000   2022-02-10

In [ ]:
employees.index
employees.columns
employees.values

array([[1, 'John Doe', 'HR', 28, 50000, '2020-05-21'],
       [2, 'Jane Smith', 'IT', 34, 75000, '2019-06-12'],
       [3, 'Bob Johnson', 'Finance', 45, 85000, '2018-07-15'],
       [4, 'Alice White', 'IT', 29, 72000, '2021-01-04'],
       [5, 'Charlie Brown', 'Marketing', 32, 68000, '2019-11-30'],
       [6, 'Eva Green', 'HR', 41, 54000, '2017-04-22'],
       [7, 'Mike Davis', 'Finance', 50, 90000, '2016-08-19'],
       [8, 'Linda Taylor', 'IT', 26, 64000, '2022-02-10'],
       [9, 'James Wilson', 'Marketing', 38, 70000, '2020-09-08'],
       [10, 'Sarah Adams', 'HR', 30, 55000, '2021-03-18']], dtype=object)

In [20]:
pd.read_csv("5_ptyrhon_for_data_analysis/practice_CSVs/employees.csv",header=None)
pd.read_csv("5_ptyrhon_for_data_analysis/practice_CSVs/employees.csv",header=None,names=["ID", "Name", "Department","bbb", "Salary","ccc"])
pd.read_csv("5_ptyrhon_for_data_analysis/practice_CSVs/employees.csv",index_col="ID")

             Name Department  Age  Salary Joining_Date
ID
1        John Doe         HR   28   50000   2020-05-21
2      Jane Smith         IT   34   75000   2019-06-12
3     Bob Johnson    Finance   45   85000   2018-07-15
4     Alice White         IT   29   72000   2021-01-04
5   Charlie Brown  Marketing   32   68000   2019-11-30
6       Eva Green         HR   41   54000   2017-04-22
7      Mike Davis    Finance   50   90000   2016-08-19
8    Linda Taylor         IT   26   64000   2022-02-10
9    James Wilson  Marketing   38   70000   2020-09-08
10    Sarah Adams         HR   30   55000   2021-03-18

## Calculating the Average Salary by Department

In [123]:
average_salary_by_dept = employees.groupby('Department')['Salary'].mean()
print("Average Salary by Department:\n")
print(average_salary_by_dept.head())

Average Salary by Department:

Department
Finance      87500.000000
HR           53000.000000
IT           70333.333333
Marketing    69000.000000
Name: Salary, dtype: float64

In [129]:
employee_count_by_dept = employees.groupby('Department')['Department'].count()
employee_count_by_dept

Department
Finance      2
HR           3
IT           3
Marketing    2
Name: Department, dtype: int64

In [124]:
employees['salary_after_raise'] = employees['Salary'] * 1.10
employees

   ID           Name Department  Age  Salary Joining_Date  salary_after_raise
0   1       John Doe         HR   28   50000   2020-05-21             55000.0
1   2     Jane Smith         IT   34   75000   2019-06-12             82500.0
2   3    Bob Johnson    Finance   45   85000   2018-07-15             93500.0
3   4    Alice White         IT   29   72000   2021-01-04             79200.0
4   5  Charlie Brown  Marketing   32   68000   2019-11-30             74800.0
5   6      Eva Green         HR   41   54000   2017-04-22             59400.0
6   7     Mike Davis    Finance   50   90000   2016-08-19             99000.0
7   8   Linda Taylor         IT   26   64000   2022-02-10             70400.0
8   9   James Wilson  Marketing   38   70000   2020-09-08             77000.0
9  10    Sarah Adams         HR   30   55000   2021-03-18             60500.0

Sorting Employees by Age in Descending Order

In [ ]:
sorted_by_age = employees.sort_values(by='Age', ascending=1)
sorted_by_age

   ID           Name Department  Age  Salary Joining_Date  salary_after_raise
7   8   Linda Taylor         IT   26   64000   2022-02-10             70400.0
0   1       John Doe         HR   28   50000   2020-05-21             55000.0
3   4    Alice White         IT   29   72000   2021-01-04             79200.0
9  10    Sarah Adams         HR   30   55000   2021-03-18             60500.0
4   5  Charlie Brown  Marketing   32   68000   2019-11-30             74800.0
1   2     Jane Smith         IT   34   75000   2019-06-12             82500.0
8   9   James Wilson  Marketing   38   70000   2020-09-08             77000.0
5   6      Eva Green         HR   41   54000   2017-04-22             59400.0
2   3    Bob Johnson    Finance   45   85000   2018-07-15             93500.0
6   7     Mike Davis    Finance   50   90000   2016-08-19             99000.0

In [ ]:
employees.Joining_Date
employees["Joining_Date"]= pd.to_datetime(employees["Joining_Date"])
employees["Joining_Date"]
recent_jops = employees[employees["Joining_Date"] > "2020-01-01"]
recent_jops
recent_jops.to_csv("recent_jobs.csv", index=False)

   ID          Name Department  Age  Salary Joining_Date  salary_after_raise
0   1      John Doe         HR   28   50000   2020-05-21             55000.0
3   4   Alice White         IT   29   72000   2021-01-04             79200.0
7   8  Linda Taylor         IT   26   64000   2022-02-10             70400.0
8   9  James Wilson  Marketing   38   70000   2020-09-08             77000.0
9  10   Sarah Adams         HR   30   55000   2021-03-18             60500.0

## hierarchical index

In [23]:
mindex=pd.read_csv("examples/csv_mindex.csv")
pd.read_csv("examples/csv_mindex.csv", index_col=["key1", "key2"])

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [38]:
result = pd.read_csv("examples/ex5.csv")
result
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

`pandas.read_csv` has a list of many default NA value representations, but these defaults can be disabled with the `keep_default_na` option:

In [147]:
result2 = pd.read_csv("examples/ex5.csv", keep_default_na=False)
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

The `na_values` option accepts a sequence of strings to add to the default list of strings recognized as missing:

In [41]:
sentinels = {"message": ["foo", "NA"], "something": ["two"]}
pd.read_csv("examples/ex5.csv", na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN


`pd.read_csv`
 ```python
 (filepath_or_buffer, *, sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, skip_blank_lines=True, parse_dates=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=<no_default>)
```


# Some <code>pandas.read_csv</code> function arguments
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Argument</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>path</code></td>
<td style="text-align: left;">String indicating filesystem location, URL, or file-like object.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sep</code> or <code>delimiter</code></td>
<td style="text-align: left;">Character sequence or regular expression to use to split fields in each row.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>header</code></td>
<td style="text-align: left;">Row number to use as column names; defaults to 0 (first row), but should be <code>None</code> if there is no header row.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>index_col</code></td>
<td style="text-align: left;">Column numbers or names to use as the row index in the result; can be a single name/number or a list of them for a hierarchical index.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>names</code></td>
<td style="text-align: left;">List of column names for result.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>skiprows</code></td>
<td style="text-align: left;">Number of rows at beginning of file to ignore or list of row numbers (starting from 0) to skip.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>na_values</code></td>
<td style="text-align: left;">Sequence of values to replace with NA. They are added to the default list unless <code>keep_default_na=False</code> is passed.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>keep_default_na</code></td>
<td style="text-align: left;">Whether to use the default NA value list or not (<code>True</code> by default).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>comment</code></td>
<td style="text-align: left;">Character(s) to split comments off the end of lines.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>parse_dates</code></td>
<td style="text-align: left;">Attempt to parse data to <code>datetime</code>; <code>False</code> by default. If <code>True</code>, will attempt to parse all columns. Otherwise, can specify a list of column numbers or names to parse. If element of list is tuple or list, will combine multiple columns together and parse to date (e.g., if date/time split across two columns).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>keep_date_col</code></td>
<td style="text-align: left;">If joining columns to parse date, keep the joined columns; <code>False</code> by default.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>converters</code></td>
<td style="text-align: left;">Dictionary containing column number or name mapping to functions (e.g., <code>{"foo": f}</code> would apply the function <code>f</code> to all values in the <code>"foo"</code> column).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>dayfirst</code></td>
<td style="text-align: left;">When parsing potentially ambiguous dates, treat as international format (e.g., 7/6/2012 -&gt; June 7, 2012); <code>False</code> by default.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>date_parser</code></td>
<td style="text-align: left;">Function to use to parse dates.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>nrows</code></td>
<td style="text-align: left;">Number of rows to read from beginning of file (not counting the header).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>iterator</code></td>
<td style="text-align: left;">Return a <code>TextFileReader</code> object for reading the file piecemeal. This object can also be used with the <code>with</code> statement.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>chunksize</code></td>
<td style="text-align: left;">For iteration, size of file chunks.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>skip_footer</code></td>
<td style="text-align: left;">Number of lines to ignore at end of file.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>verbose</code></td>
<td style="text-align: left;">Print various parsing information, like the time spent in each stage of the file conversion and memory use information.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>encoding</code></td>
<td style="text-align: left;">Text encoding (e.g., <code>"utf-8</code> for UTF-8 encoded text). Defaults to <code>"utf-8"</code> if <code>None</code>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>squeeze</code></td>
<td style="text-align: left;">If the parsed data contains only one column, return a Series.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>thousands</code></td>
<td style="text-align: left;">Separator for thousands (e.g., <code>","</code> or <code>"."</code>); default is <code>None</code>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>decimal</code></td>
<td style="text-align: left;">Decimal separator in numbers (e.g., <code>"."</code> or <code>","</code>); default is <code>"."</code>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>engine</code></td>
<td style="text-align: left;">CSV parsing and conversion engine to use; can be one of <code>"c"</code>, <code>"python"</code>, or <code>"pyarrow"</code>. The default is <code>"c"</code>, though the newer <code>"pyarrow"</code> engine can parse some files much faster. The <code>"python"</code> engine is slower but supports some features that the other engines do not.</td>
</tr>
</tbody>
</table>

In [43]:
result = pd.read_csv("examples/ex6.csv")
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

If you want to read only a small number of rows (avoiding reading the entire file), specify that with `nrows`:

In [44]:
pd.read_csv("examples/ex6.csv", nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie','sdgagd','dfgadf','sdgv vc','cbzb'],
        'Age': [25, 30, 35,28,72,64,21],
        'City': ['New York', 'Los Angeles', 'Chicago','zxcv','asdf','qwer','bnm,']}
df = pd.DataFrame(data)
df.to_csv("output.csv")
df.to_csv("output.csv", index=False)
df.to_csv("output.csv",sep="|")

# JSON Data
**JSON** (short for *JavaScript Object Notation*) has become one of the standard formats for sending data by HTTP request between web browsers and other applications. It is a much more free-form data format than a tabular text form like CSV

```python
obj =
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
```

In [ ]:
data = pd.read_json("examples/example.json")
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

# Data Cleaning and Preparation

a significant amount of time is spent on data preparation: loading, cleaning, transforming, and rearranging. Such tasks are often reported to take up 80% or more of an analyst's time. 

 Fortunately, pandas, along with the built-in Python language features, provides you with a high-level, flexible, and fast set of tools to enable you to manipulate data into the right form.

## Handling Missing Data

* Nan : Not A Number
* NA : Not Avilable

In [58]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data
float_data.isna()
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data
string_data.isna()
float_data = pd.Series([1, 2, None], dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

#  NA handling object methods
<table class="table">

<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>dropna</code></td>
<td style="text-align: left;">Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>fillna</code></td>
<td style="text-align: left;">Fill in missing data with some value or using an interpolation method such as <code>"ffill"</code> or <code>"bfill"</code>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>isna</code></td>
<td style="text-align: left;">Return Boolean values indicating which values are missing/NA.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>notna</code></td>
<td style="text-align: left;">Negation of <code>isna</code>, returns <code>True</code> for non-NA values and <code>False</code> for NA values.</td>
</tr>
</tbody>
</table>

In [61]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data
data.dropna()
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data
data.dropna()
data.dropna(how='all')
data
data[4] = np.nan
data
data.dropna(axis=1, how='all')

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

### Filling In Missing Data
Calling `fillna` with a constant replaces missing values with that value

In [107]:
df=pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4,1] = np.nan
df  
df.iloc[:2, 2] = np.nan
df.dropna()

df.fillna(0)
df.fillna(method='bfill')

/tmp/ipykernel_33747/4205153126.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

          0         1         2
0  1.545602  0.966595  0.024764
1  0.423915  0.966595  0.024764
2 -0.740444  0.966595  0.024764
3 -0.533555  0.966595 -0.921996
4  0.839338  0.966595 -0.009598
5  0.359514  0.577855  0.820659
6 -1.725576  3.004966  0.429316

Calling `fillna` with a dictionary, you can use a different fill value for each column:

In [81]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  1.821404  0.500000  0.000000
1 -1.899327  0.500000  0.000000
2  1.666960  0.500000 -1.103776
3 -0.421673  0.500000  0.396623
4 -0.288203 -0.581851 -0.252976
5  1.411244 -0.614819  0.336435
6 -0.029686 -0.414300 -2.521332

In [ ]:
df1 = pd.DataFrame(np.random.randn(5, 3))

In [97]:
df1
df1.iloc[2:, 1] = np.nan
df1.iloc[4:, 2] = np.nan
df1

          0         1         2
0  0.213887  0.804034 -0.631249
1 -0.667797 -0.789456 -0.332400
2  0.001782       NaN -1.141684
3  0.755246       NaN  1.260153
4  0.738795       NaN       NaN

In [103]:
df1.fillna(method='ffill')
df1.fillna(method="ffill", limit=2)
df1

/tmp/ipykernel_33747/390174669.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')
/tmp/ipykernel_33747/390174669.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method="ffill", limit=2)

          0         1         2
0  0.213887  0.804034 -0.631249
1 -0.667797 -0.789456 -0.332400
2  0.001782       NaN -1.141684
3  0.755246       NaN  1.260153
4  0.738795       NaN       NaN

In [104]:
df1.fillna(method='ffill')
df1.fillna(method="ffill", limit=2)
df1.fillna(method='bfill')

/tmp/ipykernel_33747/4044318826.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')
/tmp/ipykernel_33747/4044318826.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method="ffill", limit=2)
/tmp/ipykernel_33747/4044318826.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

          0         1         2
0  0.213887  0.804034 -0.631249
1 -0.667797 -0.789456 -0.332400
2  0.001782       NaN -1.141684
3  0.755246       NaN  1.260153
4  0.738795       NaN       NaN

In [ ]:
df1.fillna(method='ffill')
df1.fillna(method="ffill", limit=2)
df1

/tmp/ipykernel_33747/390174669.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')
/tmp/ipykernel_33747/390174669.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method="ffill", limit=2)

          0         1         2
0  0.213887  0.804034 -0.631249
1 -0.667797 -0.789456 -0.332400
2  0.001782       NaN -1.141684
3  0.755246       NaN  1.260153
4  0.738795       NaN       NaN

In [108]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## Data Transformation

### Removing Duplicates

In [109]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

The DataFrame method `duplicated` returns a Boolean Series indicating whether each row is a duplicate (its column values are exactly equal to those in an earlier row) or not

In [110]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

`drop_duplicates` returns a DataFrame with rows where the duplicated array is False filtered out

In [111]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data["v1"] = range(7)
data
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

`duplicated` and `drop_duplicates` by default keep the first observed value combination. Passing `keep="last"` will return the last one:

In [115]:
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [116]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

### Replacing Values

In [117]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace(-999, np.nan)
data.replace([-999, -1000], np.nan)
data.replace([-999, -1000], [np.nan, 0])
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [150]:
result2.replace('world','worlllllld')

  something  a   b   c   d     message
0       one  1   2   3   4          NA
1       two  5   6       8  worlllllld
2     three  9  10  11  12         foo